@startuml Authentication (REGISTER)

header Restaurant Reservation Sequence Diagram
footer Page %page% of %lastpage%
title "Authentication (REGISTER)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

' REGISTER
client->server ++:req.post('/auth/register')
server->routerAuth ++:app.use('/auth', auth)
routerAuth -> controllersAuth ++:register()
controllersAuth->modelUser ++:create(req.body)
modelUser ->UsersDatabase ++:UserSchema 
UsersDatabase --> modelUser --:user
controllersAuth <-- modelUser :user
controllersAuth ->  modelUser :getSignedJwtToken()
controllersAuth <-- modelUser --:signedJwtToken
controllersAuth->client --:response

@enduml